name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternative approaches could be...

  - type: dropdown
    id: priority
    attributes:
      label: 📈 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 🔧 Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Unknown - Not sure about complexity

  - type: textarea
    id: use-case
    attributes:
      label: 🎪 Use Case
      description: Describe your specific use case for this feature
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: 📚 Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        ```typescript
        // Example usage
        const example = new Example();
        ```

  - type: textarea
    id: additional
    attributes:
      label: 📋 Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have considered if this feature fits within the project's scope
          required: true
        - label: I would be willing to help implement this feature
          required: false
